namespace: sviridov
name: dataprotector
version: 0.1.0
readme: README.md
authors:
- Aleksandr Sviridov <alasbiridov@gmail.com>
description: Collections of modules to operate Microfocus Data Protector software
license:
- GPL-2.0-or-later

tags: ['microfocus','backup']

repository: https://github.com/AleksSviridov/ansible_collection_mfdp
documentation: https://github.com/AleksSviridov/ansible_collection_mfdp/blob/main/README.md
homepage: https://github.com/AleksSviridov/ansible_collection_mfdp/blob/main/README.md
issues: https://github.com/AleksSviridov/ansible_collection_mfdp/issues
